db:
  user: user
  password: password
  name: uptime_db
  storage: 1Gi

backend:
  image: uptime-backend
  tag: latest

frontend:
  image: uptime-frontend
  tag: latest

celery:
  image: uptime-backend 
  tag: latest


ingress:
  enabled: true
  className: nginx 
  hosts:
    - host: redisinsight.local
      paths:
        - path: /
          pathType: ImplementationSpecific
      