apiVersion: v1
kind: Secret
metadata:
  name: uptime-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  POSTGRES_DB: {{ .Values.db.name }}
  DATABASE_URL: postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@db:5432/{{ .Values.db.name }}