apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb }}
  DATABASE_URL: postgresql://{{ .Values.secrets.postgresUser }}:{{ .Values.secrets.postgresPassword }}@{{ .Release.Name }}-db:5432/{{ .Values.secrets.postgresDb }}
  CELERY_BROKER_URL: amqp://{{ .Values.secrets.rabbitmqUser }}:{{ .Values.secrets.rabbitmqPassword }}@rabbitmq:5672//
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword }}
  REDIS_URL: redis://:{{ .Values.secrets.redisPassword }}@{{ .Release.Name }}-redis:6379/0
